export enum ShipmentStatus {
  DRAFT = "DRAFT",
  PENDING_FINANCE_APPROVAL = "PENDING_FINANCE_APPROVAL",
  APPROVED = "APPROVED",
  REJECTED = "REJECTED",
  CREATED = "CREATED",
  ASSIGNED = "ASSIGNED",
  PICKED_UP = "PICKED_UP",
  IN_TRANSIT = "IN_TRANSIT",
  DELAYED = "DELAYED",
  ARRIVED_HUB = "ARRIVED_HUB",
  OUT_FOR_DELIVERY = "OUT_FOR_DELIVERY",
  DELIVERED = "DELIVERED",
  INCIDENT = "INCIDENT",
  CANCELLED = "CANCELLED",
}

/**
 * Structured reasons for delivery exceptions (incidents).
 * Maps 1:1 to the architectural blueprint's incident categories.
 */
export enum IncidentReason {
  CLIENT_REFUSED = "CLIENT_REFUSED",
  WRONG_ADDRESS = "WRONG_ADDRESS",
  NO_ANSWER = "NO_ANSWER",
  DAMAGED = "DAMAGED",
  VEHICLE_BREAKDOWN = "VEHICLE_BREAKDOWN",
  ROAD_ACCIDENT = "ROAD_ACCIDENT",
  CARGO_DAMAGED = "CARGO_DAMAGED",
  WAREHOUSE_DELAY = "WAREHOUSE_DELAY"
}

export enum ShipmentEventType {
  CREATED = "CREATED",
  ASSIGNED_DRIVER = "ASSIGNED_DRIVER",
  PICKED_UP = "PICKED_UP",
  IN_TRANSIT = "IN_TRANSIT",
  DELAYED = "DELAYED",
  ARRIVED_HUB = "ARRIVED_HUB",
  OUT_FOR_DELIVERY = "OUT_FOR_DELIVERY",
  DELIVERED = "DELIVERED",
  CANCELLED = "CANCELLED",
  INCIDENT_TRIGGERED = "INCIDENT_TRIGGERED", // مضاف لدعم نظام الحوادث التلقائي للـ SLA
  BATCH_SUBMITTED = "BATCH_SUBMITTED",
  BATCH_APPROVED = "BATCH_APPROVED",
  BATCH_REJECTED = "BATCH_REJECTED",
  BATCH_CANCELLED = "BATCH_CANCELLED",
  BATCH_AUTO_EXPIRED = "BATCH_AUTO_EXPIRED",
  BATCH_OVERRIDDEN = "BATCH_OVERRIDDEN"
}

export enum PaymentMethod {
  CASH_ON_DELIVERY = "COD",
  PREPAID_ONLINE = "ONLINE"
}